#   Ensure the PG gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  encoding: utf8
  database: advotar_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: advotar_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: advotar_production
  pool: 5
  username:
  password:
